# Generated by Django 5.1.1 on 2024-09-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0002_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество скачиваний'),
        ),
    ]
